In [8]:
import numpy as np
x=np.array([8,9,10,5])
x[1]

9

In [9]:
import pandas as pd

# Creating a pandas series

In [50]:
expenditure_mon = pd.Series({"travel":80 , "food":90 ,"shopping":500})
expenditure_tue = pd.Series({"travel":100, "shopping":200 , "food":300})
expenditure_mon+expenditure_tue

food        390
shopping    700
travel      180
dtype: int64

In [49]:
marks = pd.Series([70,85,100,99],index=["tejal","unnati","ravinder","praksh"])

marks

tejal        70
unnati       85
ravinder    100
praksh       99
dtype: int64

In [11]:
ser1 = pd.Series(np.array(["M","u","k","h","a","n","i"]))
ser1

0    M
1    u
2    k
3    h
4    a
5    n
6    i
dtype: object

In [12]:
print(ser1.dtype)

object

In [13]:
ser1 = pd.Series(np.array(["M","u","k","h","a","n","i"]),
                 index=["a","b","c","d","f","g","h"])
ser1

a    M
b    u
c    k
d    h
f    a
g    n
h    i
dtype: object

In [14]:
#creating  series with a list 
ser2 = pd.Series(["put","a","dent","in","the","universe"])
ser2

0         put
1           a
2        dent
3          in
4         the
5    universe
dtype: object

In [15]:
# creating series from dictionary 

ser3 = pd.Series({"Elon musk":"Entrepreneur","Albert Einstein":"Physicist","APJ Abdul kalam":"Misile man of india"})
ser3

Elon musk                 Entrepreneur
Albert Einstein              Physicist
APJ Abdul kalam    Misile man of india
dtype: object

In [16]:
print(ser3["Elon musk"])

Entrepreneur

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
ser4=pd.Series(np.arange(1,10,2))
ser4

0    1
1    3
2    5
3    7
4    9
dtype: int32

In [19]:
df = pd.DataFrame({"Name":["umesh","priyanshu","prakash"],
                    "Marks":[78,89,90]},
                 index=["a","b","c"])
df

        Name  Marks
a      umesh     78
b  priyanshu     89
c    prakash     90

In [20]:
type(df["Name"])

pandas.core.series.Series

In [21]:
type(df)

pandas.core.frame.DataFrame

In [22]:
df["Marks"]

a    78
b    89
c    90
Name: Marks, dtype: int64

In [23]:
df["Name"].dtype

dtype('O')

# Accessing elements of a Pandas Series

In [24]:
import numpy as np
import pandas as pd

elon_ai_comp=np.array(["Tesla","Starlink","X","Solarcity","xAI"])
ser=pd.Series(elon_ai_comp , index=["a","b","c","d","e"])
ser

a        Tesla
b     Starlink
c            X
d    Solarcity
e          xAI
dtype: object

In [25]:
# indexing single value
ser["a"]

'Tesla'

In [26]:
#indexing a series

ser["a":"d"]

a        Tesla
b     Starlink
c            X
d    Solarcity
dtype: object

In [27]:
# accessing 
ser["a":"e":2]

a    Tesla
c        X
e      xAI
dtype: object

In [28]:
ser[["a","c","e"]]

a    Tesla
c        X
e      xAI
dtype: object

# operation on pandas series

In [29]:
# adding two series 

s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([1,2,3],index=['a','b','c'])

res=s1+s2
print(res)

a    11
b    22
c    33
dtype: int64

In [30]:
# adding two series 

s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([1,2,3],index=['d','e','f'])

res=s1+s2
print(res)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
dtype: float64

In [31]:
# adding two series 

s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])

res=s1+s2
print(res)

a    11.0
b    22.0
c    33.0
d     NaN
e     NaN
f     NaN
dtype: float64

In [32]:
s1=pd.Series([10,20,30])
s2=pd.Series([10,25,30])

res=s1==s2
print(res)

0     True
1    False
2     True
dtype: bool

In [33]:
s1[s1==s2]

0    10
2    30
dtype: int64

In [34]:
s1[s1!=s2]

1    20
dtype: int64

In [35]:
s1[(s1>5) & (s2>20)]

1    20
2    30
dtype: int64

In [36]:
s1=pd.Series([10,20,30])
s2=pd.Series([10,25,35])

res=s1==s2
print(res)

0     True
1    False
2    False
dtype: bool

In [37]:
s1[(s1>5) & (s2>20)]

1    20
2    30
dtype: int64

In [38]:
s1[(s1>20) & (s2>20)]

2    30
dtype: int64

# Pandas series index attribute

In [39]:
data = pd.Series([10,20,30,40] , index=['a','b','c','d'])

# Accessing the index 
print("origional index",data.index)

origional index Index(['a', 'b', 'c', 'd'], dtype='object')

In [40]:
# modifying the index 

data.index=['w','x','y','z']
print("modified series:\n", data)

modified series:
 w    10
x    20
y    30
z    40
dtype: int64

In [41]:
# accessing duplicates 
import numpy as np
import pandas as pd

elon_ai_comp=np.array(["Tesla","Starlink","X","Solarcity","xAI"])
ser=pd.Series(elon_ai_comp , index=["a","a","c","d","e"])
ser

a        Tesla
a     Starlink
c            X
d    Solarcity
e          xAI
dtype: object

In [42]:
ser["a"]

a       Tesla
a    Starlink
dtype: object

In [43]:
ser.iloc[0]

'Tesla'

In [44]:
ser.iloc[1]

'Starlink'

# Resetting series index

In [45]:
# index to default
ser.reset_index()

  index          0
0     a      Tesla
1     a   Starlink
2     c          X
3     d  Solarcity
4     e        xAI

In [46]:
ser.reset_index(drop=True)

0        Tesla
1     Starlink
2            X
3    Solarcity
4          xAI
dtype: object

In [47]:
# but the change were not permanent 
ser

a        Tesla
a     Starlink
c            X
d    Solarcity
e          xAI
dtype: object

In [48]:
 # permanent change ( use inplace = True )
ser.reset_index(drop=True , inplace=True)  # permanent changed
ser

0        Tesla
1     Starlink
2            X
3    Solarcity
4          xAI
dtype: object